### ISSUE TITLE
Doesn't handle preflight requests

### ISSUE THREAD

**Issue by dandv** [watson/http-echo-server#4]
I get the error below on OPTIONS requests:

> Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4110' is therefore not allowed access.

This makes it impossible to debug any requests that follow.

Here's the request:

![image](https://user-images.githubusercontent.com/33569/45924530-5d651b80-beb7-11e8-9071-fbeebd1e38a1.png)

**Comment by watson** [comment]
Thanks for raising this issue. I've fixed it in v2.1.0 (hopefully). If it doesn't work, please let me know
